# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: gcc

# Is performed before the scripts in the stages step
before_script: 
  - apt update
  - apt -y install cmake

# Defines stages which are to be executed
stages:
  - build
  - test

build-cpp:
  stage: build
  script:
    - git submodule update --init --recursive
    - cmake -H. -Bbuild
    - cd build; make

test-cpp:
  stage: test
  script:
    - ./build/unit_tests

